CREATE TABLE IF NOT EXISTS car_table(id INT, name VARCHAR, isReserved boolean);
INSERT INTO car_table(id, name, "isreserved")
    VALUES  (1, 'BMW', true),
            (2, 'BMW', true),
            (3, 'BMW', false),
            (4, 'BMW', false),
            (5, 'BMW', true),
            (6, 'BMW', false),
            (7, 'BMW', true),
            (8, 'BMW', false),
            (9, 'BMW', false),
            (10, 'BMW', true),
            (11, 'Toyota', true),
            (12, 'Toyota', false),
            (13, 'Toyota', false),
            (14, 'Toyota', false),
            (15, 'Toyota', false),
            (16, 'Toyota', true),
            (17, 'Toyota', true),
            (18, 'Toyota', true),
            (19, 'Toyota', false),
            (20, 'Toyota', false),
            (21, 'Toyota', false);
